spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auscities
    username: root
    password: wxrshishuaige1@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

  application:
    name: demo1

server:
  port: 8088
springdoc:
  api-docs:
    version: OPENAPI_3_0
  swagger-ui:
    path: /swagger-ui.html